server:
  port: 8000

spring:
  application:
    name: Hierarchy-Api

    profiles:
      active: ub,am

azure:
cosmos:
  endpoint: https://roshancosmosdb.documents.azure.com:443/
  key: IfkIJjIG2SKoN149vdZlKLPpAxv2h5PjfBKu7FRT8WKNCqDcr1lchG6wFH68H5nBH6HUKH6tRESuACDboGV3Yw==
  database: SampleDB
  container: Users
#    connection-mode: Gateway
management:
  endpoints:
    web:
      exposure:
        include: health

#  java -jar Hierarchy-Api.jar --spring.profiles.active=ub,am


mvc:
  path match:
    matching-strategy: ANT_PATH_M