server:
  port: 8000

spring:
  application:
    name: Hierarchy-Api

azure:
  cosmos:
    endpoint: https://roshandb.documents.azure.com:443/
    key: 39GO9XCdsyROYjemYsxqs6Pk5Gs7dLyMedJJHM8lxR9VDnPF24e8cX3h1zjeVUug1hK7IrD8iRDWACDbEPboaA==
    database: SampleDB
    container: User
    connection-mode: Gateway
mvc:
  path match:
    matching-strategy: ANT_PATH_M