server:
  port: 8000

spring:
  application:
    name: Hierarchy-Api

azure:
  cosmos:
    endpoint: https://localhost:8081
    key: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    database: roshandb
    container: User
    queryMetricsEnabled: true
#    connection-mode: Gateway
mvc:
  path match:
    matching-strategy: ANT_PATH_M